### ISSUE TITLE
Isaac is stuck in both direction while colliding an horizontal wall

### ISSUE THREAD

**Issue by g33kex** [PainsPerdus/gboi-rocket#50]
When isaac collides with a rock horizontally like that:

##Isaac##
--------------  wall

And pressing down, it can't move left and right, it's stuck to the wall.

This doesn't happen when Isaac collides with a rock vertically, he can glide vertically with no issue.

Isaac should be able to move in the direction it's not colliding on both orientations.

**Comment by JeanMarieMineau** [comment]
Again, not a bug. We made this choice when designing the collision handler because it saves one call of the collision function. I agree it's not perfect, but to fix this efficiently, we need to refactor the whole code and mix movement, collision, and collision handling. Eventually, we will get here, but for the first milestone, we will stick to this design, with its flaws.

**Comment by g33kex** [comment]
I'm just reporting the issues!  
This is weird because it works fine when Isaac is colliding vertically!  Is this intended?

**Comment by JeanMarieMineau** [comment]
Yes, we had to choose if it would work horizontally or vertically
basically we have a flag for the h collision and one for the v collision, and we move issac.x, test the collision, set v flag, mode isaac.y, set h flag. In order to work both ways, we should try the h moves, v moves, and diag moves. This part of the code is still a work in progress. It does the job for now, but we will rewrite it at some point.

**Comment by g33kex** [comment]
Alright thanks, I tagged it as enhancement.

**Comment by JeanMarieMineau** [comment]
I'm refactoring the collision solvers, that should solve this issue in my next patch.

**Comment by JeanMarieMineau** [comment]
fix in #57
