### ISSUE TITLE
Game logic is in VBlank Interrupt

### ISSUE THREAD

**Issue by g33kex** [PainsPerdus/gboi-rocket#62]
Game logic should **NOT BE** in an interrupt!   
Game logic should be in the main game loop.

Then the vblank interrupt should be as quick as possible, only doing OAM and VRAM modifications. 
We'll also do the hblank opcode preparation during VBlank.

**Comment by JeanMarieMineau** [comment]
Yes Yes Yes. Working on it right now.

**Comment by JeanMarieMineau** [comment]
Ok so, we put the main logic in the main loop.
At the end of the loop we set a flag, and wait for Vblank.
In VBlank, we return if the flag is not set, else we update the screen. 
In order to keep the time between updates constant, we can use big enough counter in addition to the flag at the beginning of vblank.

**Comment by g33kex** [comment]
We don't need a vblank skip counter in vblank as long as everything that needs to run at constant time is in the main loop (ex : updating x pos according to speed, or updating animations).
You might consider adding a form of counter in the loop though, to modulate the speed/animation speed of Isaac more easily
